# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0002_auto_20171104_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='avion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aerolinea.Avion'),
        ),
    ]
