# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0003_vuelo_avion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('T', 'Turista'), ('E', 'Ejecutivo')], max_length=1)),
                ('costo', models.PositiveIntegerField()),
                ('numeroasiento', models.CharField(max_length=50)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.Pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.Vuelo')),
            ],
        ),
    ]
