# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0004_boleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avion',
            name='numero',
        ),
    ]
