# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0005_remove_avion_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='numero',
        ),
    ]
