# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0006_remove_vuelo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='dpi',
            field=models.IntegerField(null=True),
        ),
    ]
